services:
  - type: web
    name: plit99-web
    runtime: python
    buildCommand: "bash build.sh"
    startCommand: "bash start.sh"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 1
      - key: ENABLE_DATABASE
        value: false
      - key: BOOTSTRAP_DATABASE
        value: false
      - key: LOAD_FIXTURE_ON_DEPLOY
        value: false
      - key: SERVE_MEDIA_FILES
        value: true
