# Generated by Django 6.0.4 on 2026-04-13 05:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория галереи',
                'verbose_name_plural': 'Категории галереи',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('color', models.CharField(default='badge-gray', max_length=50, verbose_name='Цвет (CSS класс)')),
            ],
            options={
                'verbose_name': 'Категория новостей',
                'verbose_name_plural': 'Категории новостей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('media_type', models.CharField(choices=[('photo', 'Фотография'), ('video', 'Видео (ссылка)')], default='photo', max_length=10, verbose_name='Тип')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='Фото')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.gallerycategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Элемент галереи',
                'verbose_name_plural': 'Галерея',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(max_length=400, verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Полный текст')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='news/covers/', verbose_name='Обложка')),
                ('cover_emoji', models.CharField(default='📰', max_length=10, verbose_name='Эмодзи обложки')),
                ('cover_gradient', models.CharField(default='linear-gradient(135deg,#0D3060,#1668C0)', max_length=120, verbose_name='Градиент обложки')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Главная новость')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='core.newscategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at'],
            },
        ),
    ]
